{{- if .Values.addons.certManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-cert-manager-crds
spec:
  interval: 5m
  releaseName: cert-manager-crds
  chart:
    spec:
      chart: cert-manager-crds
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cgruenwald
        namespace: {{ .Release.Namespace }}
      version: '>= 0.0.0-0'
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- if .Values.addons.certManager.valuesOverride }}
  valuesFrom:
  - kind: Secret
    name: {{ .Release.Name }}-cert-manager-crds-values-override
    valuesKey: values
  {{- end }}

  dependsOn:
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  - name: {{ .Release.Name }}-cilium
    namespace: {{ .Release.Namespace }}
{{- if .Values.addons.certManager.valuesOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cert-manager-crds-values-override
stringData:
  values: |
    {{- toYaml .Values.addons.certManager.valuesOverride | nindent 4 }}
{{- end }}
{{- end }}
