---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-cilium
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
spec:
  interval: 5m
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: {{ .Release.Namespace }}
      reconcileStrategy: Revision
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: kube-system
  storageNamespace: kube-system
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    k8sServiceHost: {{ .Release.Name }}.{{ .Release.Namespace }}.svc
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      replicas: 1
    routingMode: tunnel
    tunnelProtocol: vxlan