apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubevirt-csi-node
  namespace: {{ .Release.Namespace }}
spec:
  interval: 24h
  url: https://cgruenwald.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-csi
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
spec:
  interval: 5m
  releaseName: csi
  chart:
    spec:
      chart: kubevirt-csi-node
      sourceRef:
        kind: HelmRepository
        name: kubevirt-csi-node
        namespace: {{ .Release.Namespace }}
      reconcileStrategy: Revision
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-kubevirt-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: kube-system
  storageNamespace: kube-system
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- with .Values.storageClass }}
  values:
    storageClass: "{{ . }}"
  {{- end }}      
   