## @section Common Parameters

## @param storageClass StorageClass used to store user data.
##
storageClass: piraeus-replicated

openshift:
  enableAnyuidSCC: false
  route:
    enabled: false
    host: kubevirt-cluster-api.example.com


cluster:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.243.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.95.0.0/16
  addons:
    coreDNS:
      dnsServiceIPs:
      - 10.95.0.10
    konnectivity:
      server:
        port: 8132
  network:
#    ingress:
#      className: openshift-default
#      extraAnnotations:
#        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#      hostname: kubevirt-cluster-01-api.example.com
    serviceType: ClusterIP
    certSANs:
    - kubevirt-cluster-api.example.com
  ## @param cluster.enableAnyuidSCC Enable the 'anyuid' Security Context Constraint (SCC) for the Serviceaccount used by kamajicontrolplane.
nodeGroups:
  md0:
    replicas: 3
    cpu: 2
    memory: 8Gi
    diskSize: 20Gi
  md1:
    minReplicas: 1
    maxReplicas: 5
    cpu: 4
    memory: 16Gi
    diskSize: 40Gi
## @section Cluster Addons
##
addons:
  ## Cert-manager: automatically creates and manages SSL/TLS certificate
  ##
  certManager:
    ## @param addons.certManager.enabled Enable cert-manager, which automatically creates and manages SSL/TLS certificates.
    ## @param addons.certManager.valuesOverride Custom values to override
    enabled: false
    valuesOverride: {}

  ## Cilium CNI plugin
  ##
  cilium:
    ## @param addons.cilium.valuesOverride Custom values to override
    valuesOverride: {}

  ## Ingress-NGINX Controller
  ##
  ingressNginx:
    ## @param addons.ingressNginx.enabled Enable the Ingress-NGINX controller (requires nodes labeled with the 'ingress-nginx' role).
    ## @param addons.ingressNginx.valuesOverride Custom values to override
    ##
    enabled: false
    ## @param addons.ingressNginx.hosts List of domain names that the parent cluster should route to this tenant cluster.
    ## e.g:
    ## hosts:
    ## - example.org
    ## - foo.example.net
    ##
    hosts: []
    valuesOverride: {}


## @section Helm Repositories
##
  ## List of Helm repositories to add to the tenant cluster.
helmRepositorys:
  - name: cgruenwald
    url: https://cgruenwald.github.io/charts
  - name: cilium
    url: https://helm.cilium.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io