{{- if .Values.openshift.route.enabled }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Values.openshift.route.host }}
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: kube-apiserver
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}  