---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress-nginx
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    targetPort: 80
  - appProtocol: https
    name: https
    port: 443
    targetPort: 443
  selector:
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
    node-role.kubernetes.io/worker: ""